name: .Net
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Setup .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100-preview.1.22110.4
        include-prerelease: true
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack Nuget
      run: dotnet pack --configuration Release
      working-directory: 
      env:
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
    - name: Release Task
      uses: nuget/nuget-client@v2
      with:
        args: push /bin/Release/*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${ secrets.NUGET_API_KEY }
